export const FETCH_PRODUCTS_STARTED = 'FETCH_PRODUCTS_STARTED';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const SET_SEARCH_PRODUCTS = 'SET_SEARCH_PRODUCTS';
export const SET_ITEM_SIZE = 'SET_ITEM_SIZE';

export const FETCH_WISHLIST_STARTED = 'FETCH_WISHLIST_STARTED';
export const SET_WISHLIST = 'SET_WISHLIST';
export const SET_FETCHED_WISHLIST = 'SET_FETCHED_WISHLIST';
export const UPDATE_WISHLIST = 'UPDATE_WISHLIST';

export const FETCH_CART_STARTED = 'FETCH_CART_STARTED';
export const SET_FETCHED_CART = 'SET_FETCHED_CART';
export const UPDATE_CART = 'UPDATE_CART';

export const AUTH_START = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_REDIRECT_PATH = 'AUTH_REDIRECT_PATH'
export const LOGOUT = 'LOGOUT';